name: Publish release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write # required for trusted publishing
      actions: read   # required to download artifacts from other workflows

    steps:
      - name: Find build artifacts
        uses: mr-smithers-excellent/find-build-artifacts-action@v1
        id: find_artifacts
        with:
          workflow: 'wheels.yml'
          commit: ${{ github.sha }}

      - name: Download artifacts from build workflow
        uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1